### ISSUE TITLE
WebUI performance issue

### ISSUE THREAD

**Issue by palokam** [EC-Release/web-ui#39]
The WebUI View tab is not loading for longer period of time ( waited for 10 min multiple times )
WebUI

Opening for @simran and @sheshank

**Comment by ayasuda2OO3** [comment]
No instances provided. The debugging effort will be done in the following instances-

WebUI: https://dev-ec.apps.ge.com/v1.1beta/ec
OAuth2: https://reg-ec.apps.ge.com/oauth/auth

@Gayatri212  please tag the users (Simran, Sheshank) for this tracker.

@iamkoushikpal-ge please propose a PR towards the issue, if the issue is identified.

**Comment by Gayatri212** [comment]
Improved performance from backend. [See MR here](https://gitlab.com/digital-fo/connectivity/enterprise-connect/platform-agnostic/webui-api/-/merge_requests/14)
